- src/repl.js
Before this commit, pressing ^D twice would exit the REPL but leave
the terminal in raw mode. Fix that by calling exit() directly instead
of closing the SIGINT listener.
That leaves just one reference to the `sigint_h` variable in repl.js,
the assignment in termInit(), but stepping through the code suggests
that's okay: the garbage collector marks it but doesn't collect it.
Fixes: https://github.com/saghul/quv/issues/18
> repl: reset tty cooked mode on ^D

- src/quv/timers.c
We must get rid of all the JS objects in the finalizer, that's rule
number 1.
Now in this case, when clear_timer is called we may drop the single
reference that holds the timer JS object (th->obj) and the finalizer
will run on the spot, de-refing it again, causing an assertion. Avoid it
by using a local variable and reseting its value before freeing it.
> timers: properly fix timer finalization

- API.md
- src/fs.c
- src/streams.c
- src/udp.c
The returned pointer must be freed with JS_FreeCString, which makes
things complicated for us, for little gain.
As such, make the API more consistent by only allowing ArrayBuffer
objects.
> misc: fix leaks when using JS_ToCStringLen

- README.md
I quickly scanned the build docs, and didn't notice the `--recursive` flag to `git clone` at first, resulting in a build failure:
```
make
cd build; cmake ../ -DCMAKE_BUILD_TYPE=Release -GNinja
-- Building in Release mode
-- Building with AppleClang 11.0.0.11000033 on Darwin-18.7.0
CMake Error at CMakeLists.txt:31 (add_subdirectory):
The source directory
/Users/humphd/repos/txiki.js/deps/libuv
does not contain a CMakeLists.txt file.
--   DISABLE_CURL: OFF
--   USE_SYSTEM_CURL: ON
-- Configuring incomplete, errors occurred!
See also "/Users/humphd/repos/txiki.js/build/CMakeFiles/CMakeOutput.log".
make: *** [build/Makefile] Error 1
```
I've added a larger note in the README for other people like me who miss it!
> Add larger note about submodules, to avoid build problems

- .github/workflows/ci.yml
- .travis.yml
- Makefile
- README.md
It makes CI testing slower because it must be installed first. It can
still be ran manually.
> build: don't use Ninja by default

- src/js/CMakeLists.txt
This allows you to specify a custom path to ```qjsc``` which is useful when cross-compiling and the version built by ```cmake``` won't run on the build system.
> Support Cross Compiling

- Dockerfile
Produces a minimal Apline image w/ tjs executable + shared libs in about 16MB of space
> minimal multi-stage Dockerfile

- src/js/bootstrap.js
- src/js/bootstrap2.js
- src/js/crypto.js
- tests/test-global-window.js
This would really help to use some polyfill properly, e.g. polyfills from Babel, from Browserify, these cannot be applied to e.g. Event class right now.
BTW, with this PR you should be able to run JSDOM from now on
1. `npm install jsdom`
2. Create the following snippet 'jsdom.browserify.src.js'
```js
const jsdom = require('jsdom')
global.jsdom = jsdom // workaround for qjs, there is no module.exports available
```
3. Run `browserify -r jsdom -s jsdom -o jsdom.browserify.js jsdom.browserify.src.js`
4. Run `jsdom.browserify.js` file within txiki.js
5. ???
6. Have fun
> Allow globals to be monkey patched

- src/private.h
- src/timers.c
- src/vm.c
- tests/run.js
- tests/test-timer.js
Fix #107 
We don't have to migrate to `UV_RUN_ONCE` for this case. This PR simply executes the microtask jobs before the `setTimeout` callback, which makes the `Promise.then` microtasks can be always cleared before `setTimeout`.
I've verified the basic and the nesting callback case in the original issue.
> core: fix promise microtask running sequence

- src/cli.c
Always evaluate a file as a module if it has the .mjs extension.
> cli: fix module detection

- src/vm.c
- tests/advanced/test-jsdom.js
This reverts commit ffa4b191eeb23984d502b183a1f521be717f1eb5.
> Revert "vm: use a 10MB default stack size"

- CMakeLists.txt
- src/curl-utils.c
- src/curl-utils.h
- src/misc.c
- src/modules.c
- src/private.h
- src/vm.c
- src/wasm.c
- src/wasm.h
- src/xhr.c
They bring essential web platform APIs. Optiong out was also not 100% correctly
implemented anyway.
> build: remove compile time disabling curl and wasm3

- src/dns.c
- src/error.c
- src/fs.c
- src/js/bundle.js
- src/js/package.json
- src/js/polyfills/base.js
- src/js/polyfills/crypto.js
- src/js/polyfills/performance.js
- src/js/polyfills/wasm.js
- src/js/polyfills/worker.js
- src/js/polyfills/xhr.js
- src/js/tjs/index.js
- src/js/tjs/stdio.js
- src/js/worker-bootstrap.js
- src/misc.c
- src/modules.c
- src/os.c
- src/private.h
- src/process.c
- src/signals.c
- src/std.c
- src/streams.c
- src/timers.c
- src/udp.c
- src/utils.h
- src/vm.c
- src/wasm.c
- src/worker.c
- src/xhr.c
Use a simple global object where we attach all the stuff and then just
delete it.
This simplifies the process since it's not an internal module.
> core: refactor bootstrap

- src/modules.c
- tests/run.js
- tests/test-abort-on-unhandled-rejection.js
- tests/test-wasm-f32.js
- tests/test-wasm-f64.js
- tests/test-wasm-i32.js
- tests/test-wasm-i64.js
- tests/test-wasm-multi.js
- tests/test-wasm-wasi.js
- tests/test-worker-et.js
- tests/test-worker.js
- tests/wasi/launcher.js
Some helpful extras that can be used on each file instead of having to
parse import.meta.url.
Only defined on actual files.
> core: add import.meta.{dirname,basename}

- .github/workflows/ci.yml
- examples/echo-client.js
- src/js/bundle.js
- src/js/tjs/sockets.js
- tests/test-pipe.js
- tests/test-tcp.js
- tests/test-udp.js
They underlying functions already are, as in, they return a Promise. By
not making the wrapper function async we allow for exceptions that the
wrapped function may raise to buddle up instead of resulting in a
rejected promise.
> sockets: don't make the read / write functions async

- .gitmodules
- CMakeLists.txt
It's available everywhere and it saves me from having to keep it up to
date. In addition, the bundled version was not tested thoroughly.
> build: remove bundled curl

- src/js/bundle.js
- src/js/repl.js
- src/js/tjs/index.js
- src/sys.c
This removes a helper function which is now unneeded. It only allowed us
to have a barrier in the backtrace, but it's actually nice to see the
full backtrace while working on the repl.
> core,repl: use indirect eval in the repl

- docs/txikijs.d.ts
- src/fs.c
- src/utils.h
- tests/test-fs-stat.js
Fixes: https://github.com/saghul/txiki.js/issues/218
> fs: fix not exposing tjs.(l)stat

- src/cli.c
- src/tjs.h
- src/vm.c
- src/worker.c
That's how we use it everywhere, make it explicit about it being for
modules only.
> core: rename TJS_EvalFile to TJS_EvalModule

- docs/txikijs.d.ts
- src/fs.c
- tests/test-fs.js
Hi,
I've come across the need for mkdir so I implemented it and it is presented here in this PR.
But I was hoping to improve on the usability of the `mode` parameter, considering octal literals are deprecated, but I'm not sure what would fit best.
In the TypeScript definition I see the `S_XXX` variable, but I can't find any of the flags mentioned added anywhere. If I've just missed them somehow, please let me know.
First thought was to declare them in fs.c e.g.
```
--- a/src/fs.c
+++ b/src/fs.c
@@ -1151,6 +1151,29 @@ static const JSCFunctionListEntry tjs_fs_funcs[] = {
TJS_CONST2("COPYFILE_EXCL", UV_FS_COPYFILE_EXCL),
TJS_CONST2("COPYFILE_FICLONE", UV_FS_COPYFILE_FICLONE),
TJS_CONST2("COPYFILE_FICLONE_FORCE", UV_FS_COPYFILE_FICLONE_FORCE),
+    TJS_CONST(S_IFMT),
+    TJS_CONST(S_IFSOCK), …
```
> fs: add mkdir()

- docs/txikijs.d.ts
- src/signals.c
- tests/test-signal.js
I've been using TypeScript for a few scripts and have noticed a some parts txikijs.d.ts are out of sync with what tjs provides.
Instances of `tjs.Error` have the `errno` property and not the `code` property.
I've described `tjs.Error` as a class with static properties, but was this deliberately avoided?
I've listed the error numbers explicitly, because `EXXX` is not useful in TypeScript.
Considering the recent push to change signal names to strings, would it also be desirable to only expose the error name strings and not the error numbers?
For signals, I've added a `Signal` type to help with type checking when using the signal names.
I've also annotated the `tjs.signal()` return type and added a test for it because I couldn't work out how to use it until I realised that you need to …
> TypeScript definition file fixes and extras

- src/timers.c
when js do not pass sencond params into setTimeout, the program will crash
```javascript
setTimeout(() => { //do something })
```
other platform like nodejs，web browser all support second params optional
> setTimeout: support second params optional

- src/js/bundle.js
- src/js/polyfills/event-target-polyfill.js
- src/js/polyfills/xhr.js
- tests/test-xhr-progress.js
Hi @saghul,
This fixes XMLHttpRequest's onprogress not receiving the progress-related values in its event due to using the Event class directly.
It was the only occurrence I found of the Event constructor being used like this.
> xhr: fix ProgressEvent parameters not being passed to onprogress

- docs/txikijs.d.ts
- src/process.c
- tests/test-exec.js
Hi @saghul,
I've been using tjs for scripting in an embedded Linux environment, and although there is no libuv helper function, being able to exec is pretty useful.
> process: added exec(cmd) wrapper around execvp()

- docs/txikijs.d.ts
- src/fs.c
When opening files for creation, it is rarely desirable to have no file
mode bits set.
This change sets the default file mode bits to 0666, which is what NodeJS
and shells set it to, allowing the umask to reduce the permissions
appropriately.
> fs: default tjs.open() mode parameter to 0666

- docs/txikijs.d.ts
- patches/text-encoding-utf-8+1.0.2.patch
- src/js/bundle.js
Sorry I missed your release with these @saghul.
> TextDecoder pollyfill improvement and TypeScript declaration fix for DirHandle

- docs/txikijs.d.ts
- src/os.c
- tests/test-fs.js
I could use chdir() via FFI, but since it's cross-platform through libuv I figured it's a pretty easy inclusion into tjs.
> os: add chdir() from libuv

- src/js/bundle.js
- src/js/tjs/stdio.js
While the libuv API does this already, that is, calling it on a pipe we only read from has no effect, it makes it clearer when coming back to this code.
> stdio: only set blocking writes on stdout/err pipes on Windows

- docs/txikijs.d.ts
- examples/echo-client-pipe.js
- examples/echo-client.js
- examples/echo-server-pipe.js
- examples/echo-server.js
- src/fs.c
- src/js/core.js
- src/js/core/tjs/eval-stdin.js
- src/js/core/tjs/run-tests.js
- src/js/core/tjs/stream-utils.js
- src/streams.c
- tests/test-pipe.js
- tests/test-tcp.js
Use null to mark EOF both for files and streams (tcp, pipes, etc).
Fixes: https://github.com/saghul/txiki.js/issues/337
> fs,streams: consolidate EOF marker

- README.md
Dependencies: `libtool`, `libcurl`, `texinfo`, `openssl`.
> Update Unix building instructions

- README.md
make
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.
After installing build-essential make builds successfully.
> Add build-essential to avoid build error

- src/curl-utils.c
- src/xhr.c
The ifdefs were wrong since they are defined as enums, we need to version check against libcurl.
> build: fix curl build warnings

- src/vm.c
Close all loop handles after the JS heap has been destroyed.
Only check the loop has been properly closed on debug builds.
> vm: make runtime shutdown more resilient

- README.md
autoconf for autoreconf, textinfo for makeinfo dependencies Debian/Ubuntu
> autoconf, textinfo dependencies Debian/Ubuntu

- src/private.h
- src/timers.c
- src/vm.c
In https://github.com/libuv/libuv/issues/3686 libuv changed when timers run respective to check handles.
Change the way we run the loop by running it again if necessary, untill there is no more work to do of the loop has been stopped.
Fixes: https://github.com/saghul/txiki.js/issues/443
> core: workaround libuv change in behavior

- CMakeLists.txt
On systems where `gcc --print-multi-os-directory` outputs something that is not `../lib`, Libffi installs to the wrong location (e.g. `lib64`) where CMake cannot find it and errors, breaking the build. This fix disables placing binaries in other places with the `--disable-multi-os-directory` configuration flag, forcing Libffi to install to `lib`.
This fix has no effect on systems where Libffi already installs to `lib`, and therefore does not break anything.
> build: fix libffi building to the wrong directory (https://github.com/saghul/txiki.js/issues/453)

- src/cli.c
- src/curl-utils.c
- src/tjs.h
- src/vm.c
Initialize curl there, while we're at it.
> core: refactor global nitialize

- src/process.c
Keep the object alive until the process exit callback has been closed, which is guaranteed.
Fixes: https://github.com/saghul/txiki.js/issues/471
> process: fix Process object being closed early in chained calls

- CMakeLists.txt
- src/ffi.c
- tests/test-ffi.js
> fix invalid memory writes

- tests/fixtures/ffi-test-lib.c
- tests/test-ffi.js
Move most ffi test to testlib instead of using libc, since libc partially differs depending on platform.
This also fixes tests on windows and macos arm.
> move most of test-ffi to own testlib

- CMakeLists.txt
- benchmark/million-timers.js
- src/hash.h
- src/js/polyfills/timers.js
- src/mem.c
- src/mem.h
- src/private.h
- src/timers.c
- src/uthash.h
- src/vm.c
- Don't use JS objects for timer handles
- Use a hash table in C rather an a Map in JS
- Allocate memory without using the JS allocator (1)
1) This is important because the libuv loop outlives the JS runtime.
Since handle closing is not sync and the callback where we need to
free the structures will be called later it's not safe to use it.
This is a small step in the direction of not using the JS allocator
for structures that embed libuv handles.
> core: refactor timers

- src/js/polyfills/performance.js
They need to return the mark / measure they create.
> polyfills: fix performance.{mark.measure}

- CMakeLists.txt
Hi,
First of all, thanks for all the work on txiki.
Currently only a command-line interface is available, but I would like to embed this javascript runtime in my own application.
Is this change something that you would be open to?
It requires only a small adaptation of the CMakeLists.txt and Makefile.
Let me know what you think.
> Allow embedding txiki in other applications

- docs/types/txikijs.d.ts
`unknown` in my opinion better matches the semantic of ts types for this situation. Functionally there is no difference since the code implementing that interface is written in js.
> Replaced `any` with `unknowns` in txikijs.d.ts

- src/curl-utils.c
- src/fswatch.c
- src/mem.c
- src/mem.h
- src/process.c
- src/signals.c
- src/streams.c
- src/udp.c
- src/vm.c
- src/worker.c
All native bindings are allocated and attached to the JS object in an opaque.
When what we attach is a native binding to a libuv handle there is a tricky situation: uv_close() is not synchronous, which means that we need to delay freeing the native object until the close callback was called. This is a problem when objects are freed as part of freeing the JS engine, since by the time the close callback is called the JS context and runtime have been freed.
In order to avoid this problem, allocate the memory for these "companion" objects with the tjs__ family of functions, which don't depend on the JS context.
This also allows us to refactor TJSFreeRuntime to a much more obvious flow. There is no need to walk and close all libuv handles, since they'll all be closed when the JS engine is …
> core: refactor how libuv companion objects are allocated

- src/sys.c
The resulting executable will be smaller and the source will be hidden. This is the same logic applied to all the bundled JS code in the runtime.
> standalone: strip source when serializing bytecode

- .github/workflows/ci.yml
This reverts commit c317bf5ec243914d7ecb710af5f8b85260fe7dc4.
> Revert "ci: temporatily exclude clang debug build"

- src/vm.c
- src/worker.c
Also avoid dumping errors unnecessarily, they'll be dumped when the runtime stops.
> core: stop runtime on unhandled errors processing jobs

- src/private.h
- src/vm.c
Cache the event constructor and the dispatchEvent function so we can call them easily when new events need to be emitted from C code.
> core: simplify unhandled promise rejection handling

- .github/workflows/release.yml
Support build on windows-x86, macos-x86, macos-arm64 
For Windows platform, all dynamic libraries required by tjs are packaged
Only tested in Windows environment https://github.com/ahaoboy/txiki.js/releases
> add release ci

- src/worker.c
- tests/helpers/worker-echo.js
- tests/test-worker-large-payload.js
When sending a payload, prefix it with its length. Then on the receiving end, we read the length and the entire buffer in chunks.
> worker: allow sending huge messages

- src/private.h
- src/vm.c
- src/worker.c
- tests/test-worker-large-payload.js
> Improve SharedArrayBuffer support

- .eslintignore
- types/src/txikijs.d.ts
- Refactored some code to expose .d.ts as typed objects and not interfaces as they are singletons. This improves the readability of the resulting documentation.
- Prevented eslint from failing due to style rules broken in the automatically generated docs
> General improvements to type docs

- src/builtins.c
`/home/wangyang/cross/.xmake/cache/packages/2408/t/txiki.js/v24.6.0/source/txiki.js/src/builtins.c:44:34: error: initializer element is not constant
{ "tjs:assert", tjs__assert, tjs__assert_size },
^~~~~~~~~~~~~~~~
/home/wangyang/cross/.xmake/cache/packages/2408/t/txiki.js/v24.6.0/source/txiki.js/src/builtins.c:44:34: note: (near initialization for ‘builtins[0].data_size’)
/home/wangyang/cross/.xmake/cache/packages/2408/t/txiki.js/v24.6.0/source/txiki.js/src/builtins.c:45:28: error: initializer element is not constant
{ "tjs:ffi", tjs__ffi, tjs__ffi_size },
^~~~~~~~~~~~~
/home/wangyang/cross/.xmake/cache/packages/2408/t/txiki.js/v24.6.0/source/txiki.js/src/builtins.c:45:28: note: (near initialization for ‘builtins[1].data_size’)
/home/wangyang/cross/.xmake/cache/packages/2408/t/txiki.js/v2 …
> fix low verion gcc build err

- src/mod_ffi.c
- src/vm.c
What we really want is an ArrayBuffer where memory is not freed when the JS object is collected, since the memory is allocated and freed by libffi.
In addition, we can remove that hack with the magic number in the SAB allocator.
> ffi: don't unnecessarily create SharedArrayBuffer instances

- src/vm.c
It's no longer needed in libuv 1.49 since closing the tty handle that set it resets it already.
> vm: remove unnecessary call to uv_tty_reset_mode

- src/mod_process.c
- src/mod_sqlite3.c
- src/utils.c
- src/utils.h
We now have an equivalent public one in QuickJS.
> utils: remove custom JS_FreePropEnum function

- README.md
Compiling on ubuntu24.04 with github runner will give an error
```
configure.ac:215: error: possibly undefined macro: LT_SYS_SYMBOL_USCORE
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
```
https://github.com/libffi/libffi/issues/210
It seems that libuv and libffi require libltdl-dev
```
sudo apt-get install libltdl-dev
```
> doc: add libltdl-dev for linux

- deps/sqlite3/CMakeLists.txt
Current cmake version (v4) does not support <3.5 anymore, so adjust the minimum version. This should fix some CI jobs.
> update sqlite3 cmake version

- src/xhr.c
Setting [CURLOPT_ACCEPT_ENCODING](https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html) to an empty string will enable compressing and decompressing of cURL, which will:
1. Automatically compress the request body and request server respond with a compressed body to reduce network traffic.
2. Automatically decompress the response body according to the `content-encoding` header in the response.
3. Make curl decompressing response body automatically when users set the `accept-encoding` header manually (some SDKs sign requests with headers, making deleting the `accept-encoding` header impossible).  
Without setting `CURLOPT_ACCEPT_ENCODING`, cURL will not decompress any response even a `content-encoding` header is set, enforcing users handle decompressing in JS with a poor performance.
> feat: enable network request compressing & decompressing
