saghul/txiki.js

CMakeLists.txt

Fixes: https://github.com/saghul/qjsuv/issues/1

build: fix undefined symbol errors, link to libm

---

src/repl.js

I'm too used to having this work. ^^

repl: make ^L clear screen

---

src/quv/modules.c

- use pstrcpy
- use the libuv provided realpath

modules: improve adding import meta

---

CMakeLists.txt
src/js/CMakeLists.txt
src/js/bootstrap2.js
src/js/event-target.js
src/qjsc.c
src/quv/vm.c

While we are at it, make window (aka global / globalThis) inherit from
it and dispatch the "load" event.

core: add EventTarget polyfill

---

src/js/url.js

Not perfect, but it should do the job.

url: add URLSearchparams polyfill

---

src/js/console.js
src/vm.c

- inspection
- formatting
- console.table

console: logging improvements

---

examples/gundb.js

<3 @saghul for adding the window bindings :) Adding this so I can share it with the vibrant Gun community

Add GunDB example

---

src/js/abort-controller.js
src/js/bootstrap2.js
src/js/event-target.js

- remove deprecated properties
- expose Event and CustomEvent objects
- use ES6 classes

js: improve EventTarget support

---

src/curl-utils.c
src/curl-utils.h
src/modules.c

Throw an error is the HTTP request failed.

curl: fix HTTP module import error handling

---

src/xhr.c

Fixes: https://github.com/saghul/quv/issues/59

xhr: fix object leak

---

TODO
src/xhr.c
tests/test-fetch.js
tests/test-xhr.js

It only supports strings for now.

xhr: add support for sending a body

---

CMakeLists.txt

Also specify this is a C project.

build: update CMake dependency

---

src/cli.c
src/std.c
src/tjs.h
src/vm.c
src/worker.c

Implement --override-filename

---

src/cli.c

Implement --strict-module-detection

---

src/js/bootstrap.js
src/js/bootstrap2.js
src/xhr.c
tests/test-worker.js
tests/test-xhr.js

Fixes: https://github.com/saghul/txiki.js/issues/78

js: add EventTarget API to XHR

---

src/cli.c
src/private.h

This is stacked onto #98 and enables module preloading like node's `-r, --require` flag does.

Preload modules

---

README.md

the submodules are huge in size, it would be better to make use of --shallow-submodules

use --shallow-submodules clone method

---

src/worker.c

libuv now has uv_socketpair, so we no longer need to roll our own!

worker: simplify code

---

README.md
src/cli.c
src/js/bundle.js
src/js/index.js
src/js/polyfills/alert-confirm-prompt.js
src/js/polyfills/base.js
src/js/polyfills/console.js
src/js/polyfills/index.js
src/js/repl.js
src/js/tjs/index.js
src/js/tjs/stdio.js
src/misc.c
src/streams.c
src/tjs.h
src/vm.c

These globals refer tho the interpreter's STDIN, STDOUT and STDERR
respectively.

tjs: add tjs.std{in,out,err}

---

src/cli.c
src/tjs.h
src/vm.c
tests/test-mem-limit.js

Fixes: https://github.com/saghul/txiki.js/issues/117

cli,core: add option for setting memory limit

---

src/dns.c
src/streams.c
src/udp.c
src/utils.c
src/utils.h
tests/test-getaddrinfo.js

Don't create an "addr" object.

core: flatten result of getaddrinfo

---

examples/echo-client-pipe.js
examples/echo-client.js
examples/echo-server-pipe.js
examples/echo-server-udp.js
examples/echo-server.js
src/dns.c
src/js/bundle.js
src/js/tjs/index.js
src/js/tjs/sockets.js
src/streams.c
src/utils.c
tests/test-pipe.js
tests/test-tcp.js
tests/test-udp.js

They are the shorthands to create TCP/UDP/Pipe sockets. The bare handles
are no longer exposed.

core: introduce tjs.connect / tjs.listen

---

src/js/bundle.js
src/js/tjs/sockets.js
src/streams.c
tests/test-pipe.js

Pipes shouldn't have a default and fail.

sockets: fixup default values for address resolution

---

src/os.c
src/process.c

When JS_ToCString is called to covert a JS object into a string, we have
to call JS_FreeCString or it will leak.

core: fix various string leaks

---

src/os.c

Fixes: https://github.com/saghul/txiki.js/issues/226

core: remove tjs.gettimeofday

---

src/error.c
tests/test-errno-codes.js

Fixes: https://github.com/saghul/txiki.js/issues/224

error: remove UV_ prefix for error constants

---

src/js/bundle.js
src/js/polyfills/index.js
src/js/tjs/alert-confirm-prompt.js
src/js/tjs/index.js

They differ slightly from the browser versions in that they are async.
Fixes: https://github.com/saghul/txiki.js/issues/223

js: move alert/confirm/prompt to the tjs namespace

---

src/os.c
tests/test-gethostname.js

Fixes: https://github.com/saghul/txiki.js/issues/221

tjs: add tjs.gethostname

---

src/os.c
tests/test-env.js

Fixes: https://github.com/saghul/txiki.js/issues/220

os: sanitize parameters passed to {get,set,unset}env

---

docs/txikijs.d.ts
src/udp.c

Fixes: https://github.com/saghul/txiki.js/issues/219

udp: fix not exporting UDP constants

---

docs/txikijs.d.ts
src/js/bundle.js
src/js/tjs/sockets.js
src/streams.c
tests/test-tcp-bindflags.js

Fixes: https://github.com/saghul/txiki.js/issues/235

tcp,udp: add support for bind flags

---

src/fs.c
src/js/bundle.js
src/js/tjs/index.js
src/js/tjs/stdio.js

Fixes: https://github.com/saghul/txiki.js/issues/210

core: support stdio over files

---

docs/tsconfig.doc.json
docs/txikijs.d.ts
src/js/bundle.js
src/js/tjs/fs.js
src/js/tjs/index.js
src/js/tjs/sockets.js
src/js/tjs/stream-utils.js
tests/test-fs-streams.js

Fixes: https://github.com/saghul/txiki.js/issues/244

fs: integrate file handles with web streams

---

docs/txikijs.d.ts
src/js/bundle.js
src/js/tjs/sockets.js
src/streams.c
tests/test-tcp.js

Fixes: https://github.com/saghul/txiki.js/issues/243

sockets: add setKeepAlive / setNoDelay

---

docs/txikijs.d.ts
src/os.c
tests/test-pid-ppid.js

Fixes: https://github.com/saghul/txiki.js/issues/249

core: add tjs.{pid,ppid}

---

docs/txikijs.d.ts
src/os.c
tests/test-userinfo.js

Fixes: https://github.com/saghul/txiki.js/issues/250

core: add tjs.userInfo()

---

docs/txikijs.d.ts
src/fs.c
src/js/bundle.js
src/js/tjs/fs.js
tests/test-fs-truncate.js

Ref: https://github.com/saghul/txiki.js/issues/247

fs: add FileHandle.truncate()

---

.gitignore
docs/txikijs.d.ts
src/js/bundle.js
src/js/repl.js
src/js/tjs/index.js
src/js/tjs/signal.js
src/signals.c

Use strings for signal names.
Ref: https://github.com/saghul/txiki.js/issues/261

tjs,signal: remove constants

---

docs/txikijs.d.ts
src/process.c
src/signals.c
src/utils.c
src/utils.h
tests/helpers/sleep.js
tests/run.js
tests/test-abort-on-unhandled-rejection.js
tests/test-eval-as-module.js
tests/test-mem-limit.js
tests/test-proc-kill.js
tests/test-wasm-wasi.js

Ref: https://github.com/saghul/txiki.js/issues/261

process: use signal names

---

docs/txikijs.d.ts
src/fs.c
src/js/bundle.js
src/js/tjs/fs.js
tests/test-fs-sync.js

Ref: https://github.com/saghul/txiki.js/issues/247

fs: add File.{sync,datasync}

---

docs/txikijs.d.ts
src/fs.c
tests/test-fs-readdir.js

Ref: https://github.com/saghul/txiki.js/issues/261

fs: introduce a DirEnt object

---

docs/txikijs.d.ts
src/fs.c
src/process.c
src/utils.c
src/utils.h
tests/test-fs.js
tests/test-kill.js

Hi,
I've added some more fs functions (chown, lchown, chmod) and the non-process-handle kill function.
The test for kill() on Windows is not very effective because of some limitations with that platform, but I dove into libuv and its own tests and it looks like it's to be expected.

Added chmod, chown, lchown, kill

---

examples/process.js

Fixes https://github.com/saghul/txiki.js/issues/291

read() and write() expect TypedArray as parameter

---

docs/intro.md

Link to https://bettercallsaghul.com/txiki.js/api/modules/tjs.html

modules/tjs.html is 404 in docs/intro.md

---

docs/txikijs.d.ts

gethostname was missing in type descriptions
Edit: and NetworkInterface.mac

Added missing typings for gethostname and NetworkInterface.mac

---

src/js/bundle.js
src/js/tjs/ffi.js
tests/fixtures/ffi-test-lib.c
tests/test-ffi.js

Hi @saghul. I found and fixed some problems with FFI.

FFI: fixed Pointer.deref() and DlSymbol.addr

---

README.md
package-lock.json
package.json
src/js/std.js
src/js/stdlib/index.js
src/js/stdlib/path.js
src/modules.c
src/private.h
src/vm.c
tests/test-fs.js

Including the win32 implementation.

path: update path module to match Node 18

---

CMakeLists.txt
src/builtins.c
src/modules.c
src/private.h
src/vm.c

Thanks @richarddd
Ref: https://github.com/saghul/txiki.js/pull/350

core: lazy load builtin stdlib modules

---

src/curl-utils.c
src/modules.c
tests/helpers/import-http-delay.js
tests/test-import-http-timeout.js

Fixes: https://github.com/saghul/txiki.js/issues/377

curl: add timeout to http imports

---

deps/quickjs/include/quickjs.h
deps/quickjs/src/quickjs.c
tests/test-builtin.js

fix: JS_NewFloat64 -O3 not support Infinity NaN

---

README.md

Substitute state for stae. Link to QuickJS-ng

Substitute state for stae. Link to QuickJS-ng

---

package-lock.json
package.json
src/js/polyfills/index.js

Ref: https://github.com/saghul/txiki.js/issues/418

polyfills: add Compression Streams API polyfill

---

tests/helpers/import-http-delay.js
tests/test-fetch.js
tests/test-xhr-abort.js
tests/test-xhr-basic.js
tests/test-xhr-body.js
tests/test-xhr-et.js
tests/test-xhr-persistent.js
tests/test-xhr-progress.js
tests/test-xhr-timeout.js

httpbin has been somewhat unreliable lately.

tests: replace httpbin.org with postman-echo.com

---

docs/types/txikijs.d.ts
src/js/polyfills/console-util.js
src/js/polyfills/console.js
tests/test-console.js

- console bugfix: Symbol keys in objects were not printed
- expose format and inspect util in tjs global API

console improvements & bugfix

---

.eslintignore

fix eslintignore to match bundles again

---

docs/types/assert.d.ts

Solving https://github.com/saghul/txiki.js/issues/504

Update assert.d.ts to solve #504

---

docs/types/txikijs.d.ts
src/posix-socket.c

add AF_UNIX to defines in posix-socket

---

src/utils.h

Fixing https://github.com/saghul/txiki.js/issues/535

Support for C++ in macros

---

Makefile

Ref: https://github.com/saghul/txiki.js/issues/347

build: portability improvements to Makefile

---

src/timers.c
src/utils.c

The current error stack trace will be printed and the exit code will be != 0.
Fixes: https://github.com/saghul/txiki.js/issues/559

core: stop engine on unhandled errors

---

src/worker.c
src/ws.c
src/xhr.c
tests/test-xhr-body.js

It takes care of calling a JS handler and handles stopping the engine if there is an exception.

worker,ws,xhr: use tjs_call_handler utility

---

docs/types/path.d.ts

Fixes https://github.com/saghul/txiki.js/issues/568

Update path.d.ts to fix some array types

---

docs/types/txikijs.d.ts

No more warnings when generating docs.

Fix txikijs.d.ts JSDOC captioning

---

docs/types/txikijs.d.ts
src/private.h
src/sys.c
tests/test-version.js
tests/test-xhr-body.js

Partially related to https://github.com/saghul/txiki.js/issues/566.

Added sqlite3 version to tjs.versions

---

.github/workflows/ci.yml

Might be something in the curl WS glue code...
Ref: https://github.com/saghul/txiki.js/issues/565

ci: downgrade Alpine container image

---

tests/test-performance.js

Fixes: https://github.com/saghul/txiki.js/issues/574

test: fix flaky performance test

---

src/mod_fs.c

Ref: https://github.com/saghul/txiki.js/issues/247

fs: add FileHandle.chown

---

examples/wasm.js

Add a simple wasm implementation of the fib function

add wasm example

---

.clang-format
.github/workflows/ci.yml
src/curl-utils.c
src/error.c
src/eval.c
src/mod_dns.c
src/mod_engine.c
src/mod_ffi.c
src/mod_fs.c
src/mod_fswatch.c
src/mod_os.c
src/mod_posix-socket.c
src/mod_process.c
src/mod_sqlite3.c
src/mod_streams.c
src/mod_sys.c
src/mod_udp.c
src/modules.c
src/signals.c
src/timers.c
src/utils.c
src/vm.c
src/wasm.c
src/worker.c
src/ws.c
src/xhr.c

misc: add InsertBraces clang-format rule

---

src/xhr.c
tests/test-xhr-headers.js

Credits go to @junsik, thank you!
Fixes: https://github.com/saghul/txiki.js/issues/672

xhr: fix crash when reusing request with headers

---

types/package.json

Small PR - Commit cfcc2e770a7069e78e61e517a42df31dcc3d94e6 moved the types \`README.md\` file. This PR adjusts sources to changes.

types: update package homepage

---

.github/workflows/ci.yml
.gitmodules

Fix compilation with Clang 17.

wasm: update wasm3

---

.github/workflows/release.yml

Updated macOS runner version and modified brew install command.

ci: fix macOS release CI
